=== accelplatform/docker-stacks/data/juggling/project/schema/accel-studio-testing-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.intra-mart.jp/accel-studio-testing-config" xmlns:tns="https://www.intra-mart.jp/accel-studio-testing-config" elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

    <simpleType name="limitInt">
        <restriction base="int">
            <minInclusive value="0" />
        </restriction>
    </simpleType>

    <simpleType name="nonEmptyString">
        <restriction base="string">
            <pattern value=".+" />
        </restriction>
    </simpleType>

    <complexType name="retry">
        <sequence>
            <element name="max-count" type="tns:limitInt" default="3" minOccurs="0"></element>
            <element name="wait-seconds" type="tns:limitInt" default="10" minOccurs="0"></element>
        </sequence>
    </complexType>

    <complexType name="agent">
        <sequence>
            <element name="timeout-seconds" type="tns:limitInt" default="1800" minOccurs="0"></element>
            <element name="retry" type="tns:retry" minOccurs="0"></element>
        </sequence>
        <attribute name="base-url" type="tns:nonEmptyString" use="required"></attribute>
    </complexType>

    <complexType name="definition">
        <sequence>
            <element name="resource-size-limit" type="tns:limitInt" default="1" minOccurs="0"></element>
            <element name="resource-total-size-limit" type="tns:limitInt" default="100" minOccurs="0"></element>
        </sequence>
    </complexType>

    <element name="accel-studio-testing-config">
        <complexType>
            <sequence>
                <element name="testing-enabled" type="boolean" default="false" minOccurs="0"></element>
                <element name="agent" type="tns:agent" minOccurs="0"></element>
                <element name="definition" type="tns:definition" minOccurs="0"></element>
            </sequence>
        </complexType>
    </element>

    <annotation>
        <appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="jp.co.intra_mart.foundation.accel_studio_testing.config" />
            </jaxb:schemaBindings>
        </appinfo>
    </annotation>

</schema>

=== accelplatform/docker-stacks/data/juggling/project/conf/accel-studio-testing-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<accel-studio-testing-config xmlns="https://www.intra-mart.jp/accel-studio-testing-config"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.intra-mart.jp/accel-studio-testing-config accel-studio-testing-config.xsd"
>

  <!--
      テスト機能を利用する場合は true に変更してください。
      If you want to use the testing function, change it to true.
      使用测试功能时请改为 true 。
  -->
  <testing-enabled>true</testing-enabled>

  <agent base-url="http://accelstudio-testing-agent:8188/accel-studio-testing-agent">
    <timeout-seconds>1800</timeout-seconds>
    <retry>
      <max-count>3</max-count>
      <wait-seconds>10</wait-seconds>
    </retry>
  </agent>

  <definition>
    <resource-size-limit>1024</resource-size-limit>
    <resource-total-size-limit>102400</resource-total-size-limit>
  </definition>

</accel-studio-testing-config>
