=== accelplatform/docker-stacks/data/juggling/project/schema/forma-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.intra-mart.jp/forma-config"
  elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.0"
  xmlns:forma="http://www.intra-mart.jp/forma-config" >

  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="jp.co.intra_mart.system.forma.config" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="forma-config">
    <complexType>
      <sequence>
        <element name="item-setting" type="forma:itemSettingType" minOccurs="1" />
        <element name="toolkit-setting" type="forma:toolkitSettingType" minOccurs="1" maxOccurs="1" />
        <element name="listdisplay-setting" type="forma:listdisplaySettingType" minOccurs="1" maxOccurs="1" />
        <element name="table-setting" type="forma:tableSettingType" minOccurs="1" maxOccurs="1" />
        <element name="imw-setting" type="forma:imwSettingType" minOccurs="1" maxOccurs="1" />
        <element name="basis-setting" type="forma:basisSettingType" minOccurs="1" maxOccurs="1" />
        <element name="image-upload-setting" type="forma:imageUploadSettingType" minOccurs="1" maxOccurs="1" />
        <element name="smartphone-setting" type="forma:smartphoneSetting" minOccurs="0" maxOccurs="1" />
        <element name="help-setting" type="forma:helpSettingType" minOccurs="1" maxOccurs="1" />
        <element name="font-setting" type="forma:fontSettingType" minOccurs="1" maxOccurs="1" />
        <element name="auto-no-setting" type="forma:autoNoSettingType" minOccurs="0" maxOccurs="1" />
        <element name="escape-full-width-percent-and-underscore-flag" type="boolean" minOccurs="1" maxOccurs="1" />
        <element name="external-indicator-flag" type="boolean" minOccurs="0" maxOccurs="1" />
        <element name="external-linkage-db-query-max-rows" type="int" minOccurs="0" maxOccurs="1" />
        <element name="transaction-file-location" type="forma:transactionFileLocationType" minOccurs="0" maxOccurs="1" />
        <element name="designer-setting" type="forma:designerSettingType" minOccurs="0" maxOccurs="1" />
      </sequence>
    </complexType>
  </element>

  <complexType name="itemSettingType">
    <sequence>
      <element name="date-format" type="string" minOccurs="1" maxOccurs="unbounded" />
      <element name="table-row-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="table-col-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="imw-stamp-list-col-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="listbox-item-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="radio-item-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="checkbox-item-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="selectbox-item-limit" type="int" minOccurs="1" maxOccurs="1" />
      <element name="selectbox-item-display-limit" type="int" minOccurs="0" maxOccurs="1" />
      <element name="exclude-itemselect" type="string" minOccurs="1" maxOccurs="unbounded" />
      <element name="richtextbox-use-imui-data-url" type="boolean" minOccurs="0" maxOccurs="1" />
      <element name="ui-theme-mode" type="string" minOccurs="0" maxOccurs="1" />
      <element name="spreadsheet-item-filelength-limit" type="int" minOccurs="0" maxOccurs="1" />
      <element name="spreadsheet-item-tablecolumn-limit" type="int" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="toolkitSettingType">
    <sequence>
      <element name="define-item" type="forma:defineItemType" minOccurs="0" maxOccurs="1" />
      <element name="default-grouping" type="forma:defaultGroupingType" minOccurs="0" maxOccurs="1" />
      <element name="grouping" type="forma:groupingType" minOccurs="0" maxOccurs="unbounded" />
      <element name="page-path" type="string" minOccurs="0" maxOccurs="1" />
      <element name="css-path" type="string" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="defineItemType" >
    <sequence>
      <element name="item-path" type="string" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="defaultGroupingType" >
    <sequence>
      <element name="group" type="forma:groupType" minOccurs="0" maxOccurs="unbounded" />
      <element name="page-path" type="string" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="groupingType" >
    <sequence>
      <element name="login-group-id" type="string" minOccurs="1" maxOccurs="1" />
      <element name="group" type="forma:groupType" minOccurs="0" maxOccurs="unbounded" />
      <element name="page-path" type="string" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="groupType">
    <sequence>
      <element name="group-id" type="string" minOccurs="1" maxOccurs="1" />
      <element name="item-id" minOccurs="0" maxOccurs="unbounded" type="forma:item-id" />
    </sequence>
    <attribute name="application-type" type="string" />
  </complexType>

  <complexType name="item-id">
    <simpleContent>
      <extension base="string">
        <attribute name="application-type" type="string" use="optional" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="fontType" >
    <sequence>
      <element name="font-name" type="string" minOccurs="1" maxOccurs="1" />
      <element name="font-values" type="string" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="listdisplaySettingType">
    <sequence>
      <element name="page_count" type="int" minOccurs="1" maxOccurs="1" />
      <element name="page_pattern" type="string" minOccurs="1" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="tableSettingType">
    <sequence>
      <element name="data_type_string" type="string" minOccurs="1" maxOccurs="1" />
      <element name="data_type_number" type="string" minOccurs="1" maxOccurs="1" />
      <element name="data_type_date" type="string" minOccurs="1" maxOccurs="1" />
      <element name="data_type_timestamp" type="string" minOccurs="1" maxOccurs="1" />
      <element name="data_type_binary" type="string" minOccurs="0" maxOccurs="1" />
      <element name="table_name_max_length" type="int" minOccurs="1" maxOccurs="1" />
      <element name="column_name_max_length" type="int" minOccurs="1" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="imwSettingType">
    <sequence>
      <element name="show_menu_tab" type="boolean" minOccurs="1" maxOccurs="1" />
      <element name="show_list_item_disp_tab" type="boolean" minOccurs="1" maxOccurs="1" />
      <element name="show_auth_setting_tab" type="boolean" minOccurs="1" maxOccurs="1" />
      <element name="show-post-history" type="boolean" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="basisSettingType">
    <sequence>
      <element name="item_label_max" type="int" minOccurs="1" maxOccurs="1" />
      <element name="label_item_max" type="int" minOccurs="1" maxOccurs="1" />
      <element name="input_id_max" type="int" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="imageUploadSettingType">
    <sequence>
      <element name="acceptFileType" type="string" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="itemType">
    <sequence>
      <element name="id" type="string" minOccurs="1" maxOccurs="1" />
      <element name="url" minOccurs="0" maxOccurs="unbounded" type="forma:url" />
      <element name="path" minOccurs="0" maxOccurs="unbounded" type="forma:path" />
    </sequence>
  </complexType>
  
  <complexType name="url">
    <simpleContent>
      <extension base="string">
        <attribute name="application-type" type="string" use="optional" />
      </extension>
    </simpleContent>
  </complexType>
  
  <complexType name="path">
    <simpleContent>
      <extension base="string">
        <attribute name="application-type" type="string" use="optional" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="helpSettingType">
    <sequence>
      <element name="itemHelpUrl" type="string" minOccurs="1" maxOccurs="1" />
      <element name="designerHelpUrl" type="string" minOccurs="1" maxOccurs="1" />
      <element name="itemType" type="forma:itemType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="fontSettingType">
    <sequence>
      <element name="fonts" type="forma:fontType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="autoNoSettingType">
    <sequence>
      <element name="retry-max" type="int" minOccurs="1" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="smartphoneSetting">
    <sequence>
      <element name="table_page_size" type="int" minOccurs="0" maxOccurs="1" />
      <element name="gridtable_page_size" type="int" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>
  
  <complexType name="transactionFileLocationType">
    <sequence>
      <element name="fileupload" type="string" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <complexType name="designerSettingType">
    <sequence>
      <element name="undo-memory-max-step" type="int" minOccurs="0" maxOccurs="1" />
    </sequence>
  </complexType>

  <group name="NewGroupDefinition">
    <sequence></sequence>
  </group>
</schema>

=== accelplatform/docker-stacks/data/juggling/project/conf/forma-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<forma-config xmlns="http://www.intra-mart.jp/forma-config"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.intra-mart.jp/forma/forma-config ../../schema/forma-config.xsd">
  <item-setting>
    <date-format>yyyy/MM/dd</date-format>
    <date-format>yyyy/M/d</date-format>
    <date-format>yyyy-MM-dd</date-format>
    <date-format>yyyy-M-d</date-format>
    <date-format>dd/MM/yyyy</date-format>
    <date-format>MM/dd/yyyy</date-format>
    <table-row-limit>50</table-row-limit>
    <table-col-limit>30</table-col-limit>
    <imw-stamp-list-col-limit>30</imw-stamp-list-col-limit>
    <listbox-item-limit>30</listbox-item-limit>
    <radio-item-limit>30</radio-item-limit>
    <checkbox-item-limit>30</checkbox-item-limit>
    <selectbox-item-limit>30</selectbox-item-limit>
    <!-- セレクトボックス スクロール表示件数
    <selectbox-item-display-limit>20</selectbox-item-display-limit>
     -->
    <exclude-itemselect>product_72_checkbox</exclude-itemselect>
    <exclude-itemselect>product_72_listbox</exclude-itemselect>
    <exclude-itemselect>product_72_radio</exclude-itemselect>
    <exclude-itemselect>product_72_selectbox</exclude-itemselect>
    <exclude-itemselect>product_72_userSelect</exclude-itemselect>
    <exclude-itemselect>product_72_departmentSelect</exclude-itemselect>
    <exclude-itemselect>product_72_departmentPostSelect</exclude-itemselect>
    <exclude-itemselect>product_72_affiliationSelect</exclude-itemselect>
    <exclude-itemselect>product_72_formaAutoNo</exclude-itemselect>
    <exclude-itemselect>product_72_func</exclude-itemselect>
    <exclude-itemselect>product_80_itemSelect</exclude-itemselect>
    <exclude-itemselect>product_80_checkbox</exclude-itemselect>
    <exclude-itemselect>product_80_radio</exclude-itemselect>
    <exclude-itemselect>product_80_selectbox</exclude-itemselect>
    <exclude-itemselect>product_80_listbox</exclude-itemselect>
    <exclude-itemselect>product_80_fileImport</exclude-itemselect>
    <exclude-itemselect>product_80_fileExport</exclude-itemselect>
    <exclude-itemselect>product_80_richtextbox</exclude-itemselect>
    <richtextbox-use-imui-data-url>false</richtextbox-use-imui-data-url>
    <ui-theme-mode>iap</ui-theme-mode>
  </item-setting>
  <toolkit-setting>
    <define-item>
      <item-path>forma/designer/types/product/72/textbox</item-path>
      <item-path>forma/designer/types/product/72/textarea</item-path>
      <item-path>forma/designer/types/product/72/number</item-path>
      <item-path>forma/designer/types/product/72/func</item-path>
      <item-path>forma/designer/types/product/72/calendar</item-path>
      <item-path>forma/designer/types/product/72/terms</item-path>
      <item-path>forma/designer/types/product/72/checkbox</item-path>
      <item-path>forma/designer/types/product/72/radio</item-path>
      <item-path>forma/designer/types/product/72/selectbox</item-path>
      <item-path>forma/designer/types/product/72/listbox</item-path>
      <item-path>forma/designer/types/product/72/hidden</item-path>
      <item-path>forma/designer/types/product/72/itemSelect</item-path>
      <item-path>forma/designer/types/product/72/label</item-path>
      <item-path>forma/designer/types/product/72/script</item-path>
      <item-path>forma/designer/types/product/72/image</item-path>
      <item-path>forma/designer/types/product/72/shape</item-path>
      <item-path>forma/designer/types/product/72/horizontalrule</item-path>
      <item-path>forma/designer/types/product/72/verticalline</item-path>
      <item-path>forma/designer/types/product/72/table</item-path>
      <item-path>forma/designer/types/product/72/fileupload</item-path>
      <item-path>forma/designer/types/product/72/userSelect</item-path>
      <item-path>forma/designer/types/product/72/departmentSelect</item-path>
      <item-path>forma/designer/types/product/72/departmentPostSelect</item-path>
      <item-path>forma/designer/types/product/72/affiliationSelect</item-path>
      <item-path>forma/designer/types/product/72/imwMatterData</item-path>
      <item-path>forma/designer/types/product/72/imwMatterFile</item-path>
      <item-path>forma/designer/types/product/72/imwMatterImage</item-path>
      <item-path>forma/designer/types/product/72/imwMatterHistory</item-path>
      <item-path>forma/designer/types/product/72/imwConfirmHistory</item-path>
      <item-path>forma/designer/types/product/72/imwStampList</item-path>
      <item-path>forma/designer/types/product/80/header</item-path>
      <item-path>forma/designer/types/product/80/registButton</item-path>
      <item-path>forma/designer/types/product/80/returnButton</item-path>
      <item-path>forma/designer/types/product/80/nextButton</item-path>
      <item-path>forma/designer/types/product/80/previousButton</item-path>
      <item-path>forma/designer/types/product/80/tempButton</item-path>
      <item-path>forma/designer/types/product/80/eventButton</item-path>
      <item-path>forma/designer/types/product/72/formaAutoNo</item-path>
      <item-path>forma/designer/types/product/extend/viewer</item-path>
      <item-path>forma/designer/types/product/80/richtextbox</item-path>
      <item-path>forma/designer/types/product/80/recycleButton</item-path>
      <!-- BIS拡張アイテム -->
      <item-path>forma/designer/types/product/80/bfRegistButton</item-path>
      <item-path>forma/designer/types/product/80/iframe</item-path>
      <item-path>forma/designer/types/product/80/itemSelect</item-path>
      <item-path>forma/designer/types/product/80/table</item-path>
      <item-path>forma/designer/types/product/80/checkbox</item-path>
      <item-path>forma/designer/types/product/80/radio</item-path>
      <item-path>forma/designer/types/product/80/selectbox</item-path>
      <item-path>forma/designer/types/product/80/listbox</item-path>
      <item-path>forma/designer/types/product/80/gridtable</item-path>
      <item-path>forma/designer/types/product/80/fileImport</item-path>
      <item-path>forma/designer/types/product/80/fileExport</item-path>
      <item-path>forma/designer/types/product/80/imwModalRegisterButton</item-path>
      <item-path>forma/designer/types/product/80/imwModalTempButton</item-path>
      <item-path>forma/designer/types/product/80/imwDirectRunButton</item-path>
      <item-path>forma/designer/types/product/80/imwDirectStopButton</item-path>
      <item-path>forma/designer/types/product/80/imwDirectBackButton</item-path>
    </define-item>
    <default-grouping>
      <group>
        <group-id>input</group-id>
        <item-id>product_72_textbox</item-id>
        <item-id>product_72_textarea</item-id>
        <item-id>product_72_number</item-id>
        <item-id>product_72_func</item-id>
        <item-id>product_72_calendar</item-id>
        <item-id>product_72_terms</item-id>
        <item-id>product_80_itemSelect</item-id>
        <item-id>product_80_table</item-id>
        <item-id>product_80_checkbox</item-id>
        <item-id>product_80_radio</item-id>
        <item-id>product_80_selectbox</item-id>
        <item-id>product_80_listbox</item-id>
        <item-id>product_72_fileupload</item-id>
        <item-id>product_80_gridtable</item-id>
        <item-id>product_80_richtextbox</item-id>
      </group>
      <group>
        <group-id>button</group-id>
        <item-id application-type="std">product_80_registButton</item-id>
        <item-id application-type="imw,bis_wkf">product_80_imwModalRegisterButton</item-id>
        <item-id application-type="bis_bf">product_80_bfRegistButton</item-id>
        <item-id>product_80_nextButton</item-id>
        <item-id>product_80_previousButton</item-id>
        <item-id>product_80_returnButton</item-id>
        <item-id application-type="std">product_80_tempButton</item-id>
        <item-id application-type="imw,bis_wkf">product_80_imwModalTempButton</item-id>
        <item-id application-type="imw,bis_wkf,bis_bf">product_80_recycleButton</item-id>
        <item-id application-type="imw,bis_wkf">product_80_imwDirectRunButton</item-id>
        <item-id application-type="imw,bis_wkf">product_80_imwDirectStopButton</item-id>
        <item-id application-type="imw,bis_wkf">product_80_imwDirectBackButton</item-id>
      </group>
      <group>
        <group-id>master</group-id>
        <item-id>product_72_userSelect</item-id>
        <item-id>product_72_departmentSelect</item-id>
        <item-id>product_72_departmentPostSelect</item-id>
        <item-id>product_72_affiliationSelect</item-id>
      </group>
      <group application-type="imw,bis_wkf,bis_bf">
        <group-id>workflow</group-id>
        <item-id>product_72_imwMatterData</item-id>
        <item-id>product_72_imwMatterFile</item-id>
        <item-id>product_72_imwMatterImage</item-id>
        <item-id>product_72_imwMatterHistory</item-id>
        <item-id application-type="imw,bis_wkf">product_72_imwConfirmHistory</item-id>
        <item-id>product_72_imwStampList</item-id>
      </group>
      <group>
        <group-id>general</group-id>
        <item-id>product_72_hidden</item-id>
        <item-id>product_72_script</item-id>
        <item-id>product_80_eventButton</item-id>
        <item-id>product_72_formaAutoNo</item-id>
        <item-id>product_80_fileImport</item-id>
        <item-id>product_80_fileExport</item-id>
        <item-id>product_80_iframe</item-id>
        <item-id>product_extend_viewer</item-id>
      </group>
      <group>
        <group-id>display</group-id>
        <item-id>product_80_header</item-id>
        <item-id>product_72_horizontalrule</item-id>
        <item-id>product_72_verticalline</item-id>
        <item-id>product_72_shape</item-id>
        <item-id>product_72_image</item-id>
        <item-id>product_72_label</item-id>
      </group>
      <group>
        <group-id>deprecated</group-id>
        <item-id>product_72_itemSelect</item-id>
        <item-id>product_72_table</item-id>
