=== accelplatform/docker-stacks/data/juggling/project/schema/storage-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://jp/co/intra-mart/foundation/service/client/file/config" xmlns:tns="http://jp/co/intra-mart/foundation/service/client/file/config" elementFormDefault="qualified">

<element name="storage-config">
  <complexType>
    <sequence>
      <element name="charset" type="string"/>
      <element name="class-name" type="string"/>
      <element name="unable-charactors" type="tns:storage-unable-charactors"/>
      <element name="storage-info" type="tns:storage-storage-info"/>
      <element name="synchronize-info" type="tns:storage-synchronize-info"/>
      <element name="permit-symlink" type="boolean" minOccurs="0" maxOccurs="1"/>
    </sequence>
  </complexType>
</element>

<complexType name="storage-storage-info">
  <all>
    <element name="root-path-name" type="string"/>
    <element name="system-directory-name" type="string"/>
    <element name="public-directory-name" type="string"/>
    <element name="group-directory-name" type="string"/>
    <element name="configuration-directory-name" type="string"/>
    <element name="conpatible-directory-name" type="string"/>
    <element name="storage-directory-name" type="string"/>
    <element name="temporary-directory-name" type="string"/>
  </all>
</complexType>

<complexType name="storage-synchronize-info">
  <all>
    <element name="synchronize-key" type="string"/>
  </all>
</complexType>

<complexType name="storage-unable-charactors">
  <sequence>
      <element name="unable-charactor" type="string" maxOccurs="unbounded" minOccurs="0"/>
  </sequence>
</complexType>

</schema>

=== accelplatform/docker-stacks/juggling-build-war/overwrite/conf/storage-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<storage-config xmlns="http://jp/co/intra-mart/foundation/service/client/file/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jp/co/intra-mart/foundation/service/client/file/config ../schema/storage-config.xsd ">
  <charset>UTF-8</charset>
  <class-name>jp.co.intra_mart.system.service.client.file.ExternalStorageLocalFileImpl</class-name>
  <unable-charactors>
    <unable-charactor>\</unable-charactor>
    <unable-charactor>:</unable-charactor>
    <unable-charactor>*</unable-charactor>
    <unable-charactor>?</unable-charactor>
    <unable-charactor>&quot;</unable-charactor>
    <unable-charactor>&lt;</unable-charactor>
    <unable-charactor>&gt;</unable-charactor>
    <unable-charactor>|</unable-charactor>
  </unable-charactors>
  <storage-info>
    <root-path-name>/data/storage</root-path-name>
    <system-directory-name>system</system-directory-name>
    <public-directory-name>public</public-directory-name>
    <group-directory-name>groups</group-directory-name>
    <configuration-directory-name>conf</configuration-directory-name>
    <conpatible-directory-name>public</conpatible-directory-name>
    <storage-directory-name>storage</storage-directory-name>
    <temporary-directory-name>temp</temporary-directory-name>
  </storage-info>
  <synchronize-info>
    <synchronize-key>im_system_storage_synchronize_key</synchronize-key>
  </synchronize-info>
</storage-config>
